# Looking ahead

 
In 2 years time I want to be working as a data scientist specializing in data engineering. My first big step and also my first big inspiration in regards to bioinformatics and data science is creating this digital portfolio as a result of the minor Data Science For Biology.

The next skill I would like to learn is controlling a database and building interactive websites, so that people who do not know data science can still enjoy the gift as it is. I will be doing a projecticum where both of these skills will be used. 

For my free 32 hours in the Data science for biology cursus, I will be studying R shiny and how to build an interactive web application. With no further experience in app design or in R shiny I need to start with the basics on building a UI for the shiny app. next I need to add components that make it interactive and user friendly.

First I will studie this page https://shiny.rstudio.com/tutorial/ en then see if I can get a running shiny app, and maybe later see if I can host it somewhere. 

**edit** I created a shiny app that makes it easy to track the monkeypox virus in the world. Check out 010_free_space.Rmd! :D

I will also be doing an internship where i will be learning to use a SQL database and translate the data to my coworkers through the magic of an interactive R.shiny website.

