---
title: "Portofolio"
author: "Timo Voskuilen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  #bookdown::html_book: default
---
# Index

Assignment 1:
-----------------------------------
Goal of this assignment:
Being able to use data from real experiments and being able to reproduce the results.

COMPLETED









Assignment 2:
-----------------------------------
Goal of this assignment:
Being able to rank experiments on open science and reproducability.

need to find a publication first









Assignment 3:
-----------------------------------
Goal of this assignment:
Being able to store my files accordingly using the Guerilla analytics framework


COMPLETED








Assignment 4:
-----------------------------------
Goal of this assignment:
Making a CV using RMarkdown


COMPLETED







 
Assignment 5:
-----------------------------------
Goal of this assignment:
Being able to learn a new skill without holding the hands of the teachers


my skill to learn would be shiny in a metagenomics environment








Assignment 6:
-----------------------------------
Goal of this assignment:
Being able to write an introduction using references and crediting those references accordingly







 
Making this a bookdown:
-----------------------------------
Goal of this assignment:
Creating a bookdown to present my work easily






 
Assignment 7:
-----------------------------------
Goal of this assignment:
Being able to use SQL to store datasets in databases









 
Assignment 8:
-----------------------------------
Goal of this assignment:
Being able to create packages to use on a later date













 
Assignment 9:
-----------------------------------
Goal of this assignment:
Being able to use parameters







Free assignment 
------------------------------------
For my free assignment i want to be specializing on shiny webapps. I find it very important to make data sciences accessable to the public, and to the people at the lab who do not have the skills of data science. An interactive shiny webapp enables you to communicate results via interactive charts, visualizations, text or tables. it is very easy for people to use and get used to. 




